services:
  db:
    image: postgres:15
    container_name: shopper_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tiger
      POSTGRES_PASSWORD: o61QpN7!4YZ.hhe
      POSTGRES_DB: shopper
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    container_name: shopper_api
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    depends_on:
      - db

  web:
    build:
      context: ./web
    container_name: shopper_web
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  db_data:
